"""Local media analysis and library services."""

from movie_maker.media.analysis import (
    AUDIO_EXTENSIONS,
    PHOTO_EXTENSIONS,
    SUPPORTED_MEDIA_EXTENSIONS,
    VIDEO_EXTENSIONS,
    FfprobeAnalyzer,
    MediaAnalysis,
    MediaAnalysisErrorCode,
    MediaAnalysisFailure,
    MediaAnalysisResult,
    MediaAnalysisSuccess,
    canonical_source_key,
    canonical_source_path,
    media_kind_for_path,
)
from movie_maker.media.library import (
    DuplicateMedia,
    ImportedMedia,
    MediaImportErrorCode,
    MediaImportFailure,
    MediaImportReport,
    MediaLibrary,
    MediaRemovalErrorCode,
    MediaRemovalFailure,
    MediaRemovalResult,
    MediaRemovalSuccess,
)
from movie_maker.media.thumbnail import (
    FfmpegThumbnailer,
    ThumbnailErrorCode,
    ThumbnailFailure,
    ThumbnailResult,
    ThumbnailSuccess,
)

__all__ = [
    "AUDIO_EXTENSIONS",
    "PHOTO_EXTENSIONS",
    "SUPPORTED_MEDIA_EXTENSIONS",
    "VIDEO_EXTENSIONS",
    "DuplicateMedia",
    "FfmpegThumbnailer",
    "FfprobeAnalyzer",
    "ImportedMedia",
    "MediaAnalysis",
    "MediaAnalysisErrorCode",
    "MediaAnalysisFailure",
    "MediaAnalysisResult",
    "MediaAnalysisSuccess",
    "MediaImportErrorCode",
    "MediaImportFailure",
    "MediaImportReport",
    "MediaLibrary",
    "MediaRemovalErrorCode",
    "MediaRemovalFailure",
    "MediaRemovalResult",
    "MediaRemovalSuccess",
    "ThumbnailErrorCode",
    "ThumbnailFailure",
    "ThumbnailResult",
    "ThumbnailSuccess",
    "canonical_source_key",
    "canonical_source_path",
    "media_kind_for_path",
]
