"""In-memory visual thumbnails generated by a shell-free FFmpeg process."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from enum import Enum

from movie_maker.media.analysis import MediaAnalysis
from movie_maker.media.process import ProcessRunner, resolve_media_tool, run_process
from movie_maker.project import MediaKind

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


class ThumbnailErrorCode(str, Enum):
    """Stable categories for expected thumbnail failures."""

    NOT_VISUAL = "not_visual"
    FFMPEG_NOT_FOUND = "ffmpeg_not_found"
    TIMEOUT = "timeout"
    PROCESS_FAILED = "process_failed"
    INVALID_OUTPUT = "invalid_output"


@dataclass(frozen=True, slots=True)
class ThumbnailSuccess:
    """A transient PNG thumbnail held outside the project model."""

    source_path: str
    png_bytes: bytes


@dataclass(frozen=True, slots=True)
class ThumbnailFailure:
    """A thumbnail failure that must not reject an analyzed media item."""

    source_path: str
    code: ThumbnailErrorCode
    message: str
    detail: str | None = None


type ThumbnailResult = ThumbnailSuccess | ThumbnailFailure


class FfmpegThumbnailer:
    """Extract one bounded visual frame to stdout without creating files."""

    def __init__(
        self,
        executable: str | None = None,
        *,
        timeout_seconds: float = 15.0,
        width: int = 320,
        height: int = 180,
        runner: ProcessRunner = run_process,
    ) -> None:
        if timeout_seconds <= 0:
            raise ValueError("FFmpeg thumbnail timeout must be positive.")
        if width <= 0 or height <= 0:
            raise ValueError("Thumbnail dimensions must be positive.")
        self._executable = executable or resolve_media_tool("ffmpeg")
        self._timeout_seconds = timeout_seconds
        self._width = width
        self._height = height
        self._runner = runner

    def create(self, analysis: MediaAnalysis) -> ThumbnailResult:
        """Return PNG bytes or an isolated typed failure for one visual item."""

        if analysis.kind not in {MediaKind.VIDEO, MediaKind.PHOTO}:
            return ThumbnailFailure(
                analysis.source_path,
                ThumbnailErrorCode.NOT_VISUAL,
                "오디오 미디어에는 썸네일이 필요하지 않습니다.",
            )

        arguments = [self._executable, "-v", "error", "-nostdin"]
        if analysis.kind is MediaKind.VIDEO and analysis.duration is not None:
            seek_nanoseconds = min(
                1_000_000_000,
                max(0, analysis.duration.nanoseconds // 10),
            )
            arguments.extend(("-ss", _format_timestamp(seek_nanoseconds)))
        arguments.extend(
            (
                "-i",
                analysis.source_path,
                "-map",
                f"0:{analysis.primary_stream_index}",
                "-frames:v",
                "1",
                "-vf",
                (
                    f"scale={self._width}:{self._height}:"
                    "force_original_aspect_ratio=decrease"
                ),
                "-f",
                "image2pipe",
                "-vcodec",
                "png",
                "pipe:1",
            )
        )

        try:
            completed = self._runner(arguments, timeout=self._timeout_seconds)
        except FileNotFoundError as error:
            return ThumbnailFailure(
                analysis.source_path,
                ThumbnailErrorCode.FFMPEG_NOT_FOUND,
                "ffmpeg 실행 파일을 찾을 수 없어 기본 아이콘을 사용합니다.",
                str(error),
            )
        except subprocess.TimeoutExpired as error:
            return ThumbnailFailure(
                analysis.source_path,
                ThumbnailErrorCode.TIMEOUT,
                "썸네일 생성 시간이 초과되어 기본 아이콘을 사용합니다.",
                str(error),
            )
        except OSError as error:
            return ThumbnailFailure(
                analysis.source_path,
                ThumbnailErrorCode.PROCESS_FAILED,
                "ffmpeg를 실행하지 못해 기본 아이콘을 사용합니다.",
                str(error),
            )

        if completed.returncode != 0:
            detail = completed.stderr.decode("utf-8", errors="replace").strip()[:1000]
            return ThumbnailFailure(
                analysis.source_path,
                ThumbnailErrorCode.PROCESS_FAILED,
                "썸네일을 만들지 못해 기본 아이콘을 사용합니다.",
                detail or None,
            )
        if not completed.stdout.startswith(PNG_SIGNATURE):
            return ThumbnailFailure(
                analysis.source_path,
                ThumbnailErrorCode.INVALID_OUTPUT,
                "올바른 썸네일 이미지가 없어 기본 아이콘을 사용합니다.",
            )
        return ThumbnailSuccess(analysis.source_path, completed.stdout)


def _format_timestamp(nanoseconds: int) -> str:
    seconds, remainder = divmod(nanoseconds, 1_000_000_000)
    return f"{seconds}.{remainder:09d}"
