"""UI-independent timeline editing commands."""

from movie_maker.timeline.advanced import (
    DeleteClipGroup,
    DuplicateTimelineClip,
    MoveAbsoluteClipGroup,
    MoveVisualClipGroup,
    TimelineEditErrorCode,
    TimelineEditRejected,
)
from movie_maker.timeline.editing import (
    DEFAULT_PHOTO_DURATION,
    MAX_PHOTO_DURATION,
    MIN_PHOTO_DURATION,
    MIN_SPLIT_DURATION,
    MIN_TIMED_CLIP_DURATION,
    AddMediaClip,
    DeleteTimelineClip,
    MoveVisualClip,
    SetPhotoDuration,
    SetPlaybackRate,
    SplitClip,
    TrimClipEnd,
    TrimClipStart,
    UpdateClipAudio,
    UpdateClipTiming,
    snap_source_time,
    source_span_duration,
)

__all__ = [
    "DEFAULT_PHOTO_DURATION",
    "MAX_PHOTO_DURATION",
    "MIN_PHOTO_DURATION",
    "MIN_SPLIT_DURATION",
    "MIN_TIMED_CLIP_DURATION",
    "AddMediaClip",
    "DeleteClipGroup",
    "DeleteTimelineClip",
    "DuplicateTimelineClip",
    "MoveAbsoluteClipGroup",
    "MoveVisualClip",
    "MoveVisualClipGroup",
    "SetPhotoDuration",
    "SetPlaybackRate",
    "SplitClip",
    "TimelineEditErrorCode",
    "TimelineEditRejected",
    "TrimClipEnd",
    "TrimClipStart",
    "UpdateClipAudio",
    "UpdateClipTiming",
    "snap_source_time",
    "source_span_duration",
]
